parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
#    env(DATABASE_URL): 'mysql://root:root@192.168.110.233:1337/db_symfony4_form'
    env(DATABASE_URL): 'mysql://root:root@192.168.1.111:1337/db_symfony4_form'
#    env(DATABASE_URL): 'mysql://root:root@192.168.1.247:1337/db_symfony4_form'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
<?php

namespace App\Controller;

use App\Entity\Candidato;
use App\Form\CandidatoType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class CandidatoController extends Controller
{
    /**
     * @Route("/candidato", name="candidato")
     * @Template("candidato/index.html.twig")
     */
    public function index(Request $request)
    {
        $candidato = new Candidato();
        $form = $this->createForm(CandidatoType::class, $candidato);

        $form->handleRequest($request);

        return [
          'form' => $form->createView()
        ];
    }
}

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
